controller:
    service:
        annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            service.beta.kubernetes.io/azure-pls-create: "true"
            service.beta.kubernetes.io/azure-pls-ip-configuration-subnet: aks-subnet
            service.beta.kubernetes.io/azure-pls-name: nginx-ingress-pls
            service.beta.kubernetes.io/azure-pls-proxy-protocol: "false"
            service.beta.kubernetes.io/azure-pls-visibility: '*'
