apiVersion: v1
kind: Service
metadata:
  name: hello-btp-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true" # Use an internal LB with PLS
    service.beta.kubernetes.io/azure-pls-create: "true"
    service.beta.kubernetes.io/azure-pls-name: hello-btp-pls
    service.beta.kubernetes.io/azure-pls-ip-configuration-subnet: aks-subnet
    service.beta.kubernetes.io/azure-pls-proxy-protocol: "false"
    service.beta.kubernetes.io/azure-pls-visibility: "*"
spec:
  type: LoadBalancer
  selector:
    app: hello-btp
  ports:
    - name: hello-btp-port
      protocol: TCP
      port: 8888
      targetPort: 80